# Generated by Django 4.0.5 on 2022-08-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fegrate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcl',
            old_name='username',
            new_name='name',
        ),
    ]
